### ISSUE TITLE
Bug: Saved file is not XML or musicXML format

### ISSUE THREAD

**Issue by aman9824** [Deys2000/actual-EECS2311Group15#15]
**Title:**

The saved file is not XML or musicXML format

**Reported By:**

Aman Patel

**Version:**

Commit ID: 044304cbf5f1b72202ca83f2417de59ef135b8b9

**Platform:**

macOS
Java SE-15
Eclipse

**Reproduction:**

Open the Da Capo as stated in User Manual and then copy-pasted the text from Guitar Tabular Samples and Click on the "Convert" button and then the "Save" button to save the file.

**Actual Result:**

The saved file is in File format i.e. Document type.

**Expected Result:**

The saved file is of format .xml or .musicXML format.

**Priority:**

High

**Severity:**

High

**Screenshot:**

<img width="1031" alt="Screen Shot 2021-03-24 at 2 38 13 PM" src="https://user-images.githubusercontent.com/57772408/112366483-3ddd2280-8caf-11eb-844e-da1f3a2947c6.png">

**Comment by Obuya** [comment]
fixed.
