### ISSUE TITLE
BUG: Incorrect File Extension for Output

### ISSUE THREAD

**Issue by tran28** [Deys2000/actual-EECS2311Group15#21]
### Bug ID#:
15.1

### Reported By:
Phuong Tran (Matthew)

### Title:
File extension of output is not of .xml or .musicxml

### Platform:
Windows 10 Education
Eclipse IDE 2020-12
Java SE-15

### Version:
Commit 044304c

### Reproduction:
Open the application, select a file (could be any text tab file - I used this [guitar text tab](https://wiki.eecs.yorku.ca/course_archive/2020-21/W/2311/_media/exampleemajor.txt)). Click *Convert* then *Save*.

### Expected:
File saved is of *.xml* or *.musicxml* extension.

### Actual:
By default, there is **no** file extension. MusicXML preview applications such as [this one](https://opensheetmusicdisplay.github.io/demo/) requires a *.xml* or *.musicxml* file type.

### Priority:
**Medium** - the user must be able to preview their MusicXML using other software after the conversion so the file export type is important 

### Severity:
**Low** - a tech-savvy user can manually add the .xml or .musicxml extension to the end of the file but the system should be considerate of all types of users

### Screenshot
No file extension assigned: 
![image](https://user-images.githubusercontent.com/46450245/112406115-f0ca7200-8ce9-11eb-8e19-2f1290fd4ef4.png)

Trying to preview the saved file  [here](https://opensheetmusicdisplay.github.io/demo/) gives the following error:
![image](https://user-images.githubusercontent.com/46450245/112406231-2a9b7880-8cea-11eb-8322-ab8f4bb3ab9f.png)

**Comment by Obuya** [comment]
fixed
