### ISSUE TITLE
Output file type not recognized as XML type

### ISSUE THREAD

**Issue by mike-jshen** [Deys2000/actual-EECS2311Group15#25]
Report by: Mike Shen 216353583
Group 15 Bug Reports

Version: 044304c

Tested on: Windows 10 Java SE 1.8

Bug Report #1: Output file type not recognized as XML type

Severity: HIGH (The output cannot be opened by any music xml file readers)

Description:
When trying to save the selected file, the output file type is stated as NONE.

Comments:
It seems like the output file is type “file” and there isn’t any way to open it. However, when checking the content outputted in the GUI, it seems to be right.

Attachments:
![image](https://user-images.githubusercontent.com/68671792/112412075-4c99f880-8cf4-11eb-9a94-8d48c71950ce.png)

![image](https://user-images.githubusercontent.com/68671792/112412091-51f74300-8cf4-11eb-9e18-6823b94f43ad.png)

**Comment by Obuya** [comment]
fixed
