### ISSUE TITLE
Bug Report #2: Wrong screen size for GUI

### ISSUE THREAD

**Issue by lianattily** [Deys2000/actual-EECS2311Group15#7]
| Attribute | Issue |
| ------------- | ------------- |
| Name  | Wrong Screen size  |
| Description | When I run the application, the top and bottom of the GUI are cut off. |
| Steps to reproduce  | Run the application on a computer with Windows 10 OS and a 13.3” screen  |
| Expected results | The GUI displays properly according to my screen dimensions |
| Actual results | The GUI is way too large and cuts off at the top and bottom |
| Operating System  | Windows 10 |
| Priority  | Medium |

User manual view:
[screenshot](https://imgur.com/JEdLrI0)
Actual view:
[screenshot2](https://imgur.com/a/AylIXWlhttps://imgur.com/hPJntAJ)

**Comment by Obuya** [comment]
new Gui will be of fixed width.
